### ISSUE TITLE
Feedback: 8.0.0 major release, breaking change, changelog?

### ISSUE THREAD

**Issue by apetro** [remarkjs/remark-validate-links#35]
Request/feedback:

Please clarify in release notes what the breaking change is that occasions a major release.

I sunk some time into validating whether it would be okay for [uPortal-app-framework to upgrade to v8](https://github.com/uPortal-Project/uportal-app-framework/pull/873).  It wasn't clear from the [8.0.0 release notes](https://github.com/remarkjs/remark-validate-links/releases/tag/8.0.0) why to regard the jump to 8 as a "breaking change" occasioning the major rather than minor version bump.

I think maybe arguably it was more a "minor" version bump (added a feature). Versioning is hard! 🤷‍♂️  A reasonable person could certainly adopt the stance that the plugin potentially breaking downstream builds by flagging new problems (broken image references) that it didn't previously flag amounts to a "breaking change". I can see it. 

What I'd have benefited from might have been a really clear statement in the release notes of what about 8 was occasioning the bump from 7 to 8, so I could triage that breakingness as a non-issue for the downstream project.

Thanks for listening!

**Comment by wooorm** [comment]
Hi @apetro, thanks for raising this issue!

Good idea, that makes sense, describing in the commit for example why something is major, minor, or patch!

The reason for https://github.com/remarkjs/remark-validate-links/commit/6920834804d180ec0c7f63b52bf82e6c2df5f2a4 being major is, as you pointed out, that messages that wouldn’t happen before, are now being emitted, meaning that if you use this plugin to lint stuff and it used to pass, it could now start failing.

For SemVer, I like thinking from left to right: is it a change? Yes, it is. Alright, a major version update.

Because unified is such a big ecosystem, with hundreds of millions of downloads and plenty users, I found that it’s often better to lean to major versions when in doubt, because someones setup will probably break.

**Comment by ChristianMurphy** [comment]
For linters/validators, how build systems pass/fail is considered part of the API surface.

Meaning:
* SemVer major: includes anything that makes rules stricter, potentially breaking builds
* SemVer minor: includes new options, keeping defaults the same
* SemVer patch: is resolving false positives

Version 8 is stricter by also checking images, making it SemVer major.
