### ISSUE TITLE
Validate links for Foliant projects

### ISSUE THREAD

**Issue by holamgadol** [remarkjs/remark-validate-links#68]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I want to use _remark-validate-links_ for linting [Foliant](https://foliant-docs.github.io/docs/) projects, especially for those using [MkDocs](https://foliant-docs.github.io/docs/backends/mkdocs/) and [CustomIDs](https://foliant-docs.github.io/docs/preprocessors/customids/)

_Remark-validate-links_  has a basic functionality for this task, but some features need to be added to suit my tasks:
- slugger for parsing anchors in headings
- possibility to verify local links according to MkDocs markdown sources structure

Do you need such functionality in this project or I just can continue my efforts in another fork?

### Solution

- add a flag for using with foliant projects
- replace github-slugger for these projects
- add some new conditions in `find-refernces.js` to verify MkDocs local links

### Alternatives

I didn't think about alternatives yet

**Comment by wooorm** [comment]
This project is more for Git repositories, such as this one, hosted on GitHub/Gitlab/Bitbucket.
I do not know Foliant but I’m guessing it’s very different and that supporting it is essentially a fork of this project?

It might be of interest to note that you can already somewhat integrate with this project: https://github.com/remarkjs/remark-validate-links#integration.

**Comment by holamgadol** [comment]
@wooorm Foliant projects are also Git repositories. These projects can be considered as a special case of MkDocs SSG repo. So these features can be used not only for Foliant, but for SSG projects.

**Comment by wooorm** [comment]
Please explain what isn’t working for them, then. Because apparently they have custom links.

**Comment by holamgadol** [comment]
Proposed features:
- extract multiple refs from headings with custom ID
  `#Long Heading {#shortref}` should produce `long-heading` and `shortref`
- treat local links according to the MkDocs directory structure
 `../../document-folder/document/#anchor` should produce `../document-folder/document.md#anchor`
- treat links like `./#heading` as a link to an anchor `heading`
- option to turn off lowercase in hash
`hash = url.slice(numberSignIndex)`

Foliant projects are hosted on GitHub/Gitlab/Bitbucket, but rendered by another tools as static web site

**Comment by wooorm** [comment]
1. should be done with a plugin to add support for that custom syntax so that remark understands it
2. you can have a plugin that rewrites URLs matching Foliant, however, I believe this is outside of the scope of this project, because this project matches how markdown files on GitHub/Gitlab/Bitbucket link to each other, and not how particular static-site generators do their work. There is a lot of logic in this project that you don’t need. A separate project that say, checks the result of any static-site generator and works on rehype instead of remark, would be more useful to you
3. I believe that works
4. I do not understand this one

> but rendered by another tools as static web site

With “hosted”, I mean that links in markdown files here, which point to other markdown files here, match according to how GitHub/Gitlab/Bitbucket do that. So in your parlance, I mean whether links will work assuming the markdown is *rendered* on GitHub/Gitlab/Bitbucket.

That is to contrast it with Foliant’s behavior that you describe, for things such as `../../document-folder/document/#anchor`. Those do not work on GitHub/Gitlab/Bitbucket.

**Comment by holamgadol** [comment]
@wooorm thank you the response. I helped me to understand my requirements better.
I'll check the possibility of a separate project for linting local links in Foliant projects

> 4. I do not understand this one

MkDocs preserve letter case in anchors, so I needed an option to turn the lowercase off
